[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]

[mcp_servers.playwright.env]

[mcp_servers.playwright.tools.browser_navigate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_click]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_close]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_console_messages]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_drag]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_evaluate]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_file_upload]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_fill_form]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_handle_dialog]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_hover]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_navigate_back]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_network_requests]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_press_key]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_resize]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_run_code]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_select_option]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_snapshot]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_tabs]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_take_screenshot]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_type]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_wait_for]
approval_mode = "approve"
